=== vohuuhuy/xml-xsl/QLTH.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="QLTH">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="DonHangNhap" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="MaDHN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="DHN[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaNCC" type="xs:string"/>
                            <xs:element name="NgayNhap" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Hang_DonHangNhap" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaDHN" type="xs:string"/>
                            <xs:element name="MaH" type="xs:string"/>
                            <xs:element name="SoLuong" type="xs:unsignedInt"/>
                            <xs:element name="GiaNhap" type="xs:unsignedInt"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="MauHang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaMH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="MH[0-9]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenMH" type="xs:string"/>
                            <xs:element name="MaNH" type="xs:string"/>
                            <xs:element name="DonVi" type="xs:string"/>
                            <xs:element name="Anh" type="xs:string"/>
                            <xs:element name="ChuThich" minOccurs="0" maxOccurs="1" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="NhaCungCap" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaNCC">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="NCC[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TenNCC" type="xs:string"/>
                            <xs:element name="QuocGia" type="xs:string"/>
                            <xs:element name="DiaChi" minOccurs="0" maxOccurs="1" type="xs:string"/>
                            <xs:element name="SDT">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="8"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Email" minOccurs="0" maxOccurs="1" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Hang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="H[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaMH" type="xs:string"/>
                            <xs:element name="MaNCC" type="xs:string"/>
                            <xs:element name="HanSuDung" type="xs:date"/>
                            <xs:element name="NgayNhap" type="xs:date"/>
                            <xs:element name="GiaNhap" type="xs:unsignedInt"/>
                            <xs:element name="SoLuong" type="xs:unsignedShort"/>
                            <xs:element name="GiaBan" type="xs:unsignedInt"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Hang_DonHangXuat" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaDHX" type="xs:string"/>
                            <xs:element name="MaH" type="xs:string"/>
                            <xs:element name="SoLuong" type="xs:unsignedShort"/>
                            <xs:element name="GiaBan" type="xs:unsignedInt"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DonHangXuat" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaDHX">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="DHX[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MaKH"/>
                            <xs:element name="NgayXuat" type="xs:date"/>
                            <xs:element name="GiamGia" type="xs:unsignedInt" />
                            <xs:element name="KieuGiamGia">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="VNĐ|%"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="MauHang_NhomHang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaMH" type="xs:string"/>
                            <xs:element name="MaNH" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="NhomHang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaNH" type="xs:string"/>
                            <xs:element name="TenNH" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="KhachHang" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaKH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="KH[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HoTen" type="xs:string"/>
                            <xs:element name="Anh" type="xs:string"/>
                            <xs:element name="DiaChi" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="SoDienThoai">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Email" type="xs:string" minOccurs="0"/>
                            <xs:element name="NgaySinh" type="xs:date"/>
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="male|female"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="NguoiDung">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MaND">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="ND[0-9]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TaiKhoan">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="8"/>
                                        <xs:maxLength value="25"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MatKhau">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="6"/>
                                        <xs:maxLength value="255"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="ChucVu">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="QUAN_LY|NHAN_VIEN"/>	
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HoTen" type="xs:string"/>
                            <xs:element name="SDT">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Anh" type="xs:string"/>
                            <xs:element name="DiaChi" type="xs:string" minOccurs="1"/>
                            <xs:element name="GioiTinh">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="male|female|other"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="DonHangNhapKey">
            <xs:selector xpath="DonHangNhap"/>
            <xs:field xpath="MaDHN"/>
        </xs:key>
        <xs:key name="HangKey">
            <xs:selector xpath="Hang"/>
            <xs:field xpath="MaH"/>
        </xs:key>
        <xs:key name="NhaCungCapKey">
            <xs:selector xpath="NhaCungCap"/>
            <xs:field xpath="MaNCC"/>
        </xs:key>
        <xs:key name="DonHangXuatKey">
            <xs:selector xpath="DonHangXuat"/>
            <xs:field xpath="MaDHX"/>
        </xs:key>

        <xs:key name="MauHangKey">
            <xs:selector xpath="MauHang"/>
            <xs:field xpath="MaMH"/>
        </xs:key>
        <xs:key name="NhomHangKey">
            <xs:selector xpath="NhomHang"/>
            <xs:field xpath="MaNH"/>
        </xs:key>
        <xs:key name="KhachHangKey">
            <xs:selector xpath="KhachHang"/>
            <xs:field xpath="MaKH"/>
        </xs:key>
        <xs:key name="NguoiDung_Key">
            <xs:selector xpath="NguoiDung"/>
            <xs:field xpath="MaND"/>
        </xs:key>
        <xs:keyref name="FK_DonHangNhap_Hang" refer="DonHangNhapKey">
            <xs:selector xpath="Hang_DonHangNhap"/>
            <xs:field xpath="MaDHN"/>
        </xs:keyref>
        <xs:keyref name="FK_Hang_DonHangNhap" refer="HangKey">
            <xs:selector xpath="Hang_DonHangNhap"/>
            <xs:field xpath="MaH"/>
        </xs:keyref>
        <xs:keyref name="FK_Hang_DonHangXuat" refer="HangKey">
            <xs:selector xpath="Hang_DonHangXuat"/>
            <xs:field xpath="MaH"/>
        </xs:keyref>
        <xs:keyref name="FK_DonHangXuat_Hang" refer="DonHangXuatKey">
            <xs:selector xpath="Hang_DonHangXuat"/>
            <xs:field xpath="MaDHX"/>
        </xs:keyref>
        <xs:keyref name="FK_MauHang_NhomHang" refer="MauHangKey">
            <xs:selector xpath="MauHang_NhomHang"/>
            <xs:field xpath="MaMH"/>
        </xs:keyref>
        <xs:keyref name="FK_NhomHang_MauHang" refer="NhomHangKey">
            <xs:selector xpath="MauHang_NhomHang"/>
            <xs:field xpath="MaNH"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== vohuuhuy/xml-xsl/QLTH.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="QLTH.xsl" ?>
<QLTH
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="QLTH.xsd"
><DonHangNhap><MaDHN>DNH001</MaDHN><MaNCC>NBL001</MaNCC><NgayNhap>2019-04-04</NgayNhap><GiamGia>0</GiamGia><KieuGiamGia>KHONG</KieuGiamGia></DonHangNhap><DonHangNhap><MaDHN>DNH002</MaDHN><MaNCC>NCD003</MaNCC><NgayNhap>20018-05-04</NgayNhap><GiamGia>0.1</GiamGia><KieuGiamGia>KHUYEN_MAI</KieuGiamGia></DonHangNhap><DonHangNhap><MaDHN>DNH003</MaDHN><MaNCC>NTH005</MaNCC><NgayNhap>2019-09-14</NgayNhap><GiamGia>0.1</GiamGia><KieuGiamGia>KHUYEN_MAI</KieuGiamGia></DonHangNhap><DonHangNhap><MaDHN>DNH004</MaDHN><MaNCC>NTH005</MaNCC><NgayNhap>2020-02-03</NgayNhap><GiamGia>0.3</GiamGia><KieuGiamGia>XA_HANG_TON</KieuGiamGia></DonHangNhap><DonHangNhap><MaDHN>DNH005</MaDHN><MaNCC>NBD002</MaNCC><NgayNhap>2020-01-11</NgayNhap><GiamGia>0.7</GiamGia><KieuGiamGia>HET_HSD</KieuGiamGia></DonHangNhap><DonHangNhap><MaDHN>DHN006</MaDHN><MaNCC>NHD004</MaNCC><NgayNhap>2020-06-22</NgayNhap></DonHangNhap><Hang_DonHangNhap><MaDHN>DNH001</MaDHN><MaH>H001</MaH><SoLuong>200</SoLuong><GiaNhap>20000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DNH002</MaDHN><MaH>H002</MaH><SoLuong>40</SoLuong><GiaNhap>8000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DNH003</MaDHN><MaH>H003</MaH><SoLuong>25</SoLuong><GiaNhap>40000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DNH004</MaDHN><MaH>H004</MaH><SoLuong>25</SoLuong><GiaNhap>45000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DNH005</MaDHN><MaH>H005</MaH><SoLuong>15</SoLuong><GiaNhap>20000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DNH005</MaDHN><MaH>H006</MaH><SoLuong>50</SoLuong><GiaNhap>200000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DHN006</MaDHN><MaH>H001</MaH><SoLuong>10</SoLuong><GiaNhap>20000</GiaNhap></Hang_DonHangNhap><Hang_DonHangNhap><MaDHN>DHN006</MaDHN><MaH>H007</MaH><SoLuong>4</SoLuong><GiaNhap>10000</GiaNhap></Hang_DonHangNhap><MauHang><MaMH>BK01</MaMH><TenMH>Bánh Cosy Mari 150G</TenMH><MaNH>NHBK</MaNH><DonVi>Gói</DonVi><Anh>Anh0</Anh></MauHang><MauHang><MaMH>BK02</MaMH><TenMH>Bánh Quế Hana 50G</TenMH><MaNH>NHBK</MaNH><DonVi>Gói</DonVi><Anh>Anh1</Anh></MauHang><MauHang><MaMH>HQ01</MaMH><TenMH>Dâu Xanh Thái Lan</TenMH><MaNH>NHHQ</MaNH><DonVi>KG</DonVi><Anh>Anh1</Anh></MauHang><MauHang><MaMH>HQ02</MaMH><TenMH>Táo Mỹ Xanh</TenMH><MaNH>NHHQ</MaNH><DonVi>KG</DonVi><Anh>Anh1</Anh></MauHang><MauHang><MaMH>VM01</MaMH><TenMH>Tiền Vàng Đốt</TenMH><MaNH>NHVM</MaNH><DonVi>Tệp</DonVi><Anh>Anh1</Anh></MauHang><MauHang><MaMH>VM02</MaMH><TenMH>Hương Quy Nhan</TenMH><MaNH>NHVM</MaNH><DonVi>Búp</DonVi><Anh>Anh1</Anh></MauHang><MauHang><MaMH>VM03</MaMH><TenMH>Rượu Cúng</TenMH><MaNH>NHVM</MaNH><DonVi>Chai</DonVi><Anh>Anh111</Anh></MauHang><MauHang><MaMH>BR01</MaMH><TenMH>Bia Sài Gòn Large</TenMH><MaNH>NHBR</MaNH><DonVi>Két</DonVi><Anh>Anh1</Anh></MauHang><NhaCungCap><MaNCC>NBL001</MaNCC><TenNCC>Bân Lâm</TenNCC><QuocGia>Việt Nam</QuocGia><SDT>099999999</SDT></NhaCungCap><NhaCungCap><MaNCC>NBD002</MaNCC><TenNCC>Bình Đường</TenNCC><QuocGia>Việt Nam</QuocGia><SDT>0971111640</SDT></NhaCungCap><NhaCungCap><MaNCC>NCD003</MaNCC><TenNCC>Cảnh Đề</TenNCC><QuocGia>Việt Nam</QuocGia><SDT>0976567999</SDT></NhaCungCap><NhaCungCap><MaNCC>NHD004</MaNCC><TenNCC>Hợi Đồng</TenNCC><QuocGia>Việt Nam</QuocGia><SDT>0888186567</SDT></NhaCungCap><NhaCungCap><MaNCC>NTH005</MaNCC><TenNCC>Thúy Hương</TenNCC><QuocGia>Việt Nam</QuocGia><SDT>0868193668</SDT></NhaCungCap><Hang><MaH>H001</MaH><MaMH>BK01</MaMH><MaNCC>NCD003</MaNCC><HanSuDung>2021-09-15</HanSuDung><GiaNhap>20000</GiaNhap><SoLuong>110</SoLuong><GiaBan>23000</GiaBan><SoLuongThem>10</SoLuongThem></Hang><Hang><MaH>H002</MaH><MaMH>BK02</MaMH><MaNCC>NTH005</MaNCC><HanSuDung>2020-06-12</HanSuDung><GiaNhap>25000</GiaNhap><SoLuong>200</SoLuong><GiaBan>28000</GiaBan></Hang><Hang><MaH>H003</MaH><MaMH>HQ01</MaMH><MaNCC>NTH005</MaNCC><HanSuDung>2020-06-12</HanSuDung><GiaNhap>10000</GiaNhap><SoLuong>120</SoLuong><GiaBan>12000</GiaBan></Hang><Hang><MaH>H004</MaH><MaMH>HQ02</MaMH><MaNCC>NTH005</MaNCC><HanSuDung>2020-06-12</HanSuDung><GiaNhap>48500</GiaNhap><SoLuong>66</SoLuong><GiaBan>50000</GiaBan></Hang><Hang><MaH>H005</MaH><MaMH>VM01</MaMH><MaNCC>NHD004</MaNCC><HanSuDung>2020-06-12</HanSuDung><GiaNhap>27200</GiaNhap><SoLuong>450</SoLuong><GiaBan>30000</GiaBan></Hang><Hang><MaH>H006</MaH><MaMH>VM03</MaMH><MaNCC>NHD004</MaNCC><HanSuDung>2020-06-12</HanSuDung><GiaNhap>220000</GiaNhap><SoLuong>20</SoLuong><GiaBan>245000</GiaBan></Hang><Hang><MaH>H007</MaH><MaMH>HQ02</MaMH><MaNCC>NHD004</MaNCC><HanSuDung>2020-11-12</HanSuDung><GiaNhap>10000</GiaNhap><SoLuong>4</SoLuong></Hang><MauHang_NhomHang><MaMH>BK01</MaMH><MaNH>NHBK</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>BK02</MaMH><MaNH>NHBK</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>HQ01</MaMH><MaNH>NHHQ</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>HQ02</MaMH><MaNH>NHHQ</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>VM01</MaMH><MaNH>NHVM</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>VM02</MaMH><MaNH>NHVM</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>VM03</MaMH><MaNH>NHVM</MaNH></MauHang_NhomHang><MauHang_NhomHang><MaMH>BR01</MaMH><MaNH>NHBR</MaNH></MauHang_NhomHang><DonHangXuat><MaDHX>DHX001</MaDHX><MaKH>KH001</MaKH><NgayXuat>2006-05-04</NgayXuat><GiamGia>0.3</GiamGia><KieuGiamGia>KHUYEN_MAI</KieuGiamGia></DonHangXuat><DonHangXuat><MaDHX>DHX002</MaDHX><MaKH>KH003</MaKH><NgayXuat>2006-05-04</NgayXuat><GiamGia>0.7</GiamGia><KieuGiamGia>XA_HANG_TON</KieuGiamGia></DonHangXuat><Hang_DonHangXuat><MaDHX>DHX001</MaDHX><MaH>H003</MaH><SoLuong>32768</SoLuong><GiaBan>214748364</GiaBan></Hang_DonHangXuat><Hang_DonHangXuat><MaDHX>DHX001</MaDHX><MaH>H005</MaH><SoLuong>32768</SoLuong><GiaBan>214748364</GiaBan></Hang_DonHangXuat><Hang_DonHangXuat><MaDHX>DHX002</MaDHX><MaH>H001</MaH><SoLuong>32768</SoLuong><GiaBan>214748364</GiaBan></Hang_DonHangXuat><Hang_DonHangXuat><MaDHX>DHX001</MaDHX><MaH>H006</MaH><SoLuong>32768</SoLuong><GiaBan>214748364</GiaBan></Hang_DonHangXuat><NhomHang><MaNH>NHBK</MaNH><TenNH>Bánh Kẹo</TenNH></NhomHang><NhomHang><MaNH>NHHQ</MaNH><TenNH>Hoa Quả</TenNH></NhomHang><NguoiDung><MaND>ND001</MaND><TaiKhoan>AdminTH1</TaiKhoan><MatKhau>MatKhau0</MatKhau><ChucVu>QUAN_LY</ChucVu><HoTen>Võ Hữu Huy</HoTen><SDT>0911118891</SDT><Anh>Anh114</Anh><DiaChi>Ninh Hiệp, Ninh Hòa, Nha Trang</DiaChi><GioiTinh>female</GioiTinh></NguoiDung><NguoiDung><MaND>ND002</MaND><TaiKhoan>AdminTH2</TaiKhoan><MatKhau>MatKhau0</MatKhau><ChucVu>NHAN_VIEN</ChucVu><HoTen>Võ Sơn Vang</HoTen><SDT>0911118891</SDT><Anh>Anh114</Anh><DiaChi>Ninh Hiệp, Ninh Hòa, Nha Trang</DiaChi><GioiTinh>male</GioiTinh></NguoiDung><NguoiDung><MaND>ND003</MaND><TaiKhoan>AdminTH3</TaiKhoan><MatKhau>MatKhau0</MatKhau><ChucVu>NHAN_VIEN</ChucVu><HoTen>Ngô Đắc Lương</HoTen><SDT>0911118891</SDT><Anh>Anh114</Anh><DiaChi>Ninh Hiệp, Ninh Hòa, Nha Trang</DiaChi><GioiTinh>male</GioiTinh></NguoiDung><NguoiDung><MaND>ND004</MaND><TaiKhoan>AdminTH4</TaiKhoan><MatKhau>MatKhau0</MatKhau><ChucVu>NHAN_VIEN</ChucVu><HoTen>Nguyễn Đình Thuận</HoTen><SDT>0911118891</SDT><Anh>Anh114</Anh><DiaChi>Ninh Hiệp, Ninh Hòa, Nha Trang</DiaChi><GioiTinh>female</GioiTinh></NguoiDung><NguoiDung><MaND>ND005</MaND><TaiKhoan>AdminTH5</TaiKhoan><MatKhau>MatKhau0</MatKhau><ChucVu>QUAN_LY</ChucVu><HoTen>Diệp Tư Thịnh</HoTen><SDT>0911118891</SDT><Anh>Anh114</Anh><DiaChi>Ninh Hiệp, Ninh Hòa, Nha Trang</DiaChi><GioiTinh>male</GioiTinh></NguoiDung><KhachHang><MaKH>KH01</MaKH><HoTen>Khách vãng lai</HoTen><Email>lai.khach@gmail.com</Email><SoDienThoai>0928716981</SoDienThoai><NgaySinh></NgaySinh><GioiTinh>male</GioiTinh><DiaChi></DiaChi></KhachHang></QLTH>
